### ISSUE TITLE
Add "Jump To Cursor" Debugger Support

### ISSUE THREAD

**Issue by mlancione** [JaneySprings/DotNet.Meteor#138]
It would be very useful to add support for "Jump To Cursor" to the debugger. This feature is not currently available.

Test environment: iOS Simulator on MacOS

**Comment by JaneySprings** [comment]
You can try to default VSCode feature, it works like **Jump to cursor**, not a **Force jump to cursor**.
![image](https://github.com/user-attachments/assets/ce34bbce-7ab7-4b34-8041-462156f6e387)

**Comment by mlancione** [comment]
"Run to Line" isn't the same as "Jump to cursor". Run to Line will execute all lines from the current line to the selected line. Jump to cursor will skip all line execution and place the program cursor at the selected line.

The MAUI extension has both "Run to Cursor" and "Jump to Cursor" as seen below:

<img width="256" alt="image" src="https://github.com/user-attachments/assets/81d5ef39-60c2-430a-8fba-5bbdf8ce89e3">

**Comment by JaneySprings** [comment]
Implemented in `6.0.2`. Check for extension updates in VSCode.
Now `Jump to cursor` item is available in the context menu:
https://github.com/user-attachments/assets/87dca864-dcdf-4a05-b7f4-9e16effa1328

Feel free to ask any questions or report bugs

**Comment by mlancione** [comment]
Thanks for the quick work. However, I'm getting this error when using Jump to Cursor on even the next line or previous line in the same method:
"Unable to set the next statement. The next statement cannot be set to another function."

I'm using an iOS Simulator. I noticed in your video you tested on Android. Could this be the reason?

Here is the log if it's helpful:
`08:11:35.7687|<--   C (gotoTargets-85): {"command":"gotoTargets","arguments":{"source":{"name":"<REDACTED>","path":"/Users/<REDACTED>","sources":[],"checksums":[]},"line":811,"column":14},"type":"request","seq":85}
08:11:35.7699|--> R (gotoTargets-85): {"type":"response","request_seq":85,"success":true,"command":"gotoTargets","body":{"targets":[{"id":1001,"label":"Jump to cursor","line":811,"column":14,"endLine":0,"endColumn":0}]},"seq":573}
08:11:35.7755|<--   C (goto-86): {"command":"goto","arguments":{"threadId":16,"targetId":1001},"type":"request","seq":86}
08:11:35.7771|[Handled] Unable to set the next statement. The next statement cannot be set to another function.: System.NotSupportedException: Unable to set the next statement. The next statement cannot be set to another function.
   at Mono.Debugging.Soft.SoftDebuggerSession.OnSetNextStatement(Int64 threadId, String fileName, Int32 line, Int32 column) in /Users/runner/work/1/s/src/Mono.Debugger/Mono.Debugging.Soft/SoftDebuggerSession.cs:line 1100
   at Mono.Debugging.Client.DebuggerSession.SetNextStatement(String fileName, Int32 line, Int32 column) in /Users/runner/work/1/s/src/Mono.Debugger/Mono.Debugging/Mono.Debugging.Client/DebuggerSession.cs:line 663
   at DotNet.Meteor.Debug.DebugSession.<>c__DisplayClass29_0.<HandleGotoRequest>b__0() in /Users/runner/work/1/s/src/DotNet.Meteor.Debug/DebugSession.cs:line 470
   at DotNet.Meteor.Debug.Extensions.ServerExtensions.DoSafe[T](Func`1 handler, Action finalizer) in /Users/runner/work/1/s/src/DotNet.Meteor.Debug/Extensions/ServerExtensions.cs:line 64
08:11:35.7781|--> R (goto-86): {"type":"response","request_seq":86,"success":false,"command":"goto","message":"Unable to set the next statement. The next statement cannot be set to another function.","body":{"error":{"id":0,"format":"Unable to set the next statement. The next statement cannot be set to another function.","url":"file:///<REDACTED>/.vscode/extensions/nromanov.dotnet-meteor-6.0.2-darwin-arm64/extension/bin/Debug/logs/Debug.log"}},"seq":574}
08:11:37.9738|<--   C (setBreakpoints-87): {"command":"setBreakpoints","arguments":{"source":{"name”:”<REDACTED>.cs","path”:”/<REDACTED>,”sources":[],"checksums":[]},"lines":[811,813],"breakpoints":[{"line":811},{"line":813}],"sourceModified":false},"type":"request","seq":87}
08:11:37.9758|--> R (setBreakpoints-87): {"type":"response","request_seq":87,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"id":11925648,"verified":false,"message":"The breakpoint will not currently be hit","line":811,"column":1,"BoundBreakpoints":[]},{"id":66892154,"verified":false,"message":"The breakpoint will not currently be hit","line":813,"column":1,"BoundBreakpoints":[]}]},"seq":575}
08:11:38.0091|[Info] Resolved pending breakpoint at '/Users/<REDACTED>' to void <REDACTED> () [0x004cc].
08:11:38.0091|--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[Mono] Resolved pending breakpoint at '/Users/<REDACTED> <REDACTED>' to void <REDACTED> () [0x004cc].\n"},"seq":576}
08:11:38.0175|--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":11925648,"verified":true,"message":"","line":811,"column":1,"BoundBreakpoints":[]}},"seq":577}
08:11:38.0182|[Info] Resolved pending breakpoint at '/Users/<REDACTED>' to void <REDACTED> () [0x004e8].
08:11:38.0182|--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[Mono] Resolved pending breakpoint at '/Users/<REDACTED>' to void <REDACTED> () [0x004e8].\n"},"seq":578}
08:11:38.0197|--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":66892154,"verified":true,"message":"","line":813,"column":1,"BoundBreakpoints":[]}},"seq":579}
08:11:39.5681|<--   C (setBreakpoints-88): {"command":"setBreakpoints","arguments":{"source":{"name":"<REDACTED>","path":"/Users/<REDACTED>","sources":[],"checksums":[]},"lines":[811],"breakpoints":[{"line":811}],"sourceModified":false},"type":"request","seq":88}
08:11:39.5695|--> R (setBreakpoints-88): {"type":"response","request_seq":88,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"id":57356923,"verified":false,"message":"The breakpoint will not currently be hit","line":811,"column":1,"BoundBreakpoints":[]}]},"seq":580}
08:11:39.5713|[Info] Resolved pending breakpoint at '/Users/<REDACTED>' to void <REDACTED> () [0x004cc].
08:11:39.5713|--> E (output): {"type":"event","event":"output","body":{"category":"stdout","output":"[Mono] Resolved pending breakpoint at '/Users/<REDACTED>' to void <REDACTED> () [0x004cc].\n"},"seq":581}
08:11:39.5789|--> E (breakpoint): {"type":"event","event":"breakpoint","body":{"reason":"changed","breakpoint":{"id":57356923,"verified":true,"message":"","line":811,"column":1,"BoundBreakpoints":[]}},"seq":582}
08:11:45.9361|<--   C (evaluate-89): {"command":"evaluate","arguments":{"expression":"videoDepthMapFrame","frameId":1000,"context":"hover","line":821,"column":60,"source":{"name":"<REDACTED>","path":"/Users/<REDACTED>","sources":[],"checksums":[]}},"type":"request","seq":89}
08:11:45.9520|--> R (evaluate-89): {"type":"response","request_seq":89,"success":false,"command":"evaluate","message":"not available","body":{},"seq":583}`

**Comment by JaneySprings** [comment]
Can you try to set the cursor position before the method name and select `Jump to cursor`? 
![image](https://github.com/user-attachments/assets/9d1f54bc-a093-4333-8ce1-9d4b30d9b585)

**Comment by mlancione** [comment]
Setting the cursor position at the start of the line then selecting Jump to Cursor worked. Should the default behavior be to always jump to the start of the current cursor line regardless of the exact cursor position within the line? This is how Visual Studio and Visual Studio Mac work.

**Comment by JaneySprings** [comment]
It seems like Mono.Debugger finds the exact method that has the same **line** and **column**.

![image](https://github.com/user-attachments/assets/c0e0583d-130e-45b4-9ebb-b7bdef6e6c61)

I think that we can change this implementation and get the last method, where `column <= method.column`

**Comment by mlancione** [comment]
Ok that sounds good.

On a side note, I noticed in your videos you have the run buttons at the top integrated in your search bar in VSCode. Is that an extension that you are using to configure that?

**Comment by JaneySprings** [comment]
No, its default VSCode setting:
![image](https://github.com/user-attachments/assets/9123f084-b307-4056-a306-d3487c63b3b6)

**Comment by JaneySprings** [comment]
I have published this fix in `6.0.3`. I also test JumpToCursor with complex expressions, it should work:
![image](https://github.com/user-attachments/assets/f79be908-2105-41aa-9f9e-aee8e55c1976)

**Comment by mlancione** [comment]
It's still failing for me when the cursor is placed in the middle of a method name.

<img width="144" alt="image" src="https://github.com/user-attachments/assets/33063928-0f17-4684-a481-096d45b7515f">

I looked at FindLocationByMethod and if the method.Locations list is in order can you simply remove the column checks completely and break out of the foreach as soon as a target is found for the line number?

**Comment by mlancione** [comment]
Actually, I think always passing 1 as the column number is the simpler solution.

**Comment by JaneySprings** [comment]
> I think always passing 1 as the column number is the simpler solution

Yes, I think that it is the best think that we can do. 
Check the following code:
```csharp
// Default mono implementation
if (line == location.LineNumber && (column <= 1 || column == location.ColumnNumber)) {
//...
}

// Fallback to any column
if (target == null && column != -1)
    target = FindLocationByMethod (method, file, line, -1, ref insideTypeRange);
```

We will use any column If the user doesn't use the exact location for JumpToCursor

**Comment by JaneySprings** [comment]
Fixed in '6.0.4'. Everything should be OK 

![image](https://github.com/user-attachments/assets/e0f11c69-3c42-4bbe-b1e6-bab9fc190668)

**Comment by mlancione** [comment]
Works great now. Thanks!
